source/report_gsm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('account/', include("accounts.urls"))
]

source/webapp/urls.py
from django.urls import path
from webapp.views.index import IndexView
from webapp.views.fuel_consumption import FuelConsumptionCreateView
from webapp.views.dispatcher import DispatcherIndexView
from webapp.views.dashboard import DashboardIndexView

urlpatterns = [
    path('', IndexView.as_view(), name='homepage'),
    path('fuel_consumption/create/<int:pk>', FuelConsumptionCreateView.as_view(), name='fuel_consumption_create'),
    path('fuel_consumption/', DispatcherIndexView.as_view(), name='fuel_consumption'),
    path('dashboards/', DashboardIndexView.as_view(), name='dashboards')
]

source/webapp/forms.py
from django import forms
from django.contrib.auth import get_user_model


# class SearchForm(forms.Form):
#     search = forms.CharField(max_length=100, required=False, label="Поиск",
#                              widget=forms.TextInput
#                                    (attrs={
#                                  "placeholder" : "Введите гос.номер"
#                                }))

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

class FuelConsumptionForm(forms.Form):
    refueling_liters = forms.CharField(required=True, label='Литры')

source/webapp/views/search.py
import json
from datetime import datetime
from django.core.serializers import serialize
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import ensure_csrf_cookie
from webapp.models import Cars


def json_cars(request, *args, **kwargs):
    if request.method == 'GET':
        search = request.GET.get('search')
        cars = Cars.objects.filter(government_number__icontains=search) if search else Cars.objects.all()
        return JsonResponse(list(cars.values(*('id', 'brand', 'model', 'government_number'))), safe=False)
    if request.method == 'POST' and request.body:
        car = json.loads(request.body)
        try:
            car = Cars.objects.create(**car)
            response = JsonResponse(car.as_dict)
            response.status_code = 201
        except Exception as e:
            response_data = {"detail": "Некорректный набор полей."}
            response = JsonResponse(response_data)
            response.status_code = 400
        return response

source/templates/partial/search.html
{% load static %}
{% load django_bootstrap5 %}

{% bootstrap_form form %}


<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script>
    let search = $('#id_search');
    let url = 'http://127.0.0.1:8000/json-cars/?search='

    let addCar = function (cars, container){
        let pk = document.createElement('div');
        let government_number = document.createElement('p');
        government_number.innerText = `government_number - ${cars.government_number}`;
        let link = document.createElement('a');
        link.innerText = 'Подробнее';
        $(link).attr('href', `http://127.0.0.1:8000/car/detail/${cars.id}`)
        console.log($(link).attr('href', `http://127.0.0.1:8000/car/detail/${cars.id}`))
        pk.append(government_number);
        console.log(government_number)
        pk.append(link);
        container.append(pk);
    }
    renderResults = function(cars){
        let car_container = $('#cars');
        car_container.empty();
        for(let car of cars){
            addCar(car, car_container);
        }
    }
    let getCars = function (){
        let value = search.val();
        $.ajax({
            url: url + value
        }).done(
            function (data){
                renderResults(data);
            }
        )
    }
    search.on('keyup', getCars);

</script>

source/templates/partial/simple_search.html
<form class="text-center" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <button type="submit"><i class="bi bi-search" style="font-size: 18px;"></i></button>
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>